language: ruby
rvm:
  - "2.5.9"
  - "2.6.7"
  - "2.7.2"
  - "2.7.3"
gemfile:
  - gemfiles/http4.gemfile
  - gemfiles/http5.gemfile
  - gemfiles/rack1.gemfile
  - gemfiles/rack2.gemfile

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
# workaround for https://github.com/travis-ci/travis-ci/issues/5239:
before_install:
  - gem install bundler
